Repository cardbox/backend, pull requests merged in 2021-08, with the labels that each got.

#39 Cache dockerfile and use rustls instead of openssl
  .github/workflows/image-api.yml
  Cargo.lock
  Dockerfile
  api-internal/Cargo.toml
  api-internal/src/main.rs
  app/src/lib.rs
  app/src/services.rs
  builder.Dockerfile
  config/default-development.toml
  config/default.toml
  db/Cargo.toml
  db/src/lib.rs
  migrations.Dockerfile
  settings/src/lib.rs
  start-tools.Dockerfile
Labels: feature

#42 Use opentelemetry_jaeger upfront
  .env.sample
  .github/workflows/image-api.yml
  Cargo.lock
  app/Cargo.toml
  app/src/configure.rs
Labels: feature

#44 BOX-152: Update api-internal scheme
  api-internal/openapi.yaml
Labels: API:Internal, Improvement, Frontend

#43 BOX-111: implement cards list method
  api-internal/openapi.yaml
  api-internal/src/generated.rs
  api-internal/src/main.rs
  api-internal/src/routes/cards/list.rs
  api-internal/src/routes/cards/mod.rs
  app/src/cards.rs
  core/src/app/cards.rs
  core/src/contracts/repo/card.rs
  db/src/repos/card.rs
  sqlx-data.json
Labels: API:Internal, Backend

#46 BOX-185: Update cards.list contract
  api-internal/openapi.yaml
Labels: Frontend, Refactoring

#48 Feature/users.get
  api-internal/src/generated.rs
  api-internal/src/main.rs
  api-internal/src/routes/cards/search.rs
  api-internal/src/routes/mod.rs
  api-internal/src/routes/users/get.rs
  api-internal/src/routes/users/mod.rs
  app/src/lib.rs
  app/src/users.rs
  core/src/app/mod.rs
  core/src/app/users.rs
  core/src/contracts/repo/user.rs
  core/src/models/mod.rs
  core/src/models/socials.rs
  core/src/models/user.rs
  db/src/entities/mod.rs
  db/src/entities/socials.rs
  db/src/entities/user.rs
  db/src/repos/user.rs
  migrations/20210808141535_username_optional.down.sql
  migrations/20210808141535_username_optional.up.sql
  sqlx-data.json
Labels: feature

#47 Feature/session.get
  Dockerfile
  api-internal/src/generated.rs
  api-internal/src/main.rs
  api-internal/src/routes/mod.rs
  api-internal/src/routes/session/get.rs
  api-internal/src/routes/session/mod.rs
  api-internal/src/routes/users/get.rs
  app/src/configure.rs
  app/src/users.rs
  config/default-development.toml
  config/default.toml
  core/src/app/users.rs
  core/src/contracts/repo/user.rs
  core/src/models/user.rs
  db/src/entities/mod.rs
  db/src/entities/session_token.rs
  db/src/entities/user.rs
  db/src/repos/user.rs
  migrations/20210808163851_drop_socials_unique.down.sql
  migrations/20210808163851_drop_socials_unique.up.sql
  settings/src/lib.rs
  sqlx-data.json
Labels: feature

#53 BOX-195 Fix UserInfo to have id property
  api-internal/src/generated.rs
  api-internal/src/routes/accesso/auth_done.rs
Labels: feature
